config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get '/about', to: 'pages#about'
  get '/search', to: 'pages#search'

  resources :pages

end

app/models/page.rb
class Page < ActiveRecord::Base
	belongs_to :user
  validates :title, presence: true, length: {minimum: 3}
	validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :pages
	validates :name, uniqueness: { case_sensitive: false }
						#length: { minimum: 3, maximum: 25 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 105 },
						uniqueness: { case_sensitive: false },
						format: { with: VALID_EMAIL_REGEX }
	before_save { self.email = email.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	before_action :set_page, only: [:edit, :update, :show, :destroy]
	before_action :set_locale
	def set_locale
		I18n.locale = params[:locale] || I18n.default_locale
		if !params[:locale].nil?
			I18n.default_locale = params[:locale]
		end
	end

  def home
  end

  def index
    @pages = Page.all
  end

  def new
    @page = Page.new
  end

  def create
    @page = Page.new(page_params)
		@page.user = User.first
    if @page.save
      flash[:success] = t(:page_created)
      redirect_to page_path(@page)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @page.update(page_params)
		flash[:success] = t(:page_updated)
		render 'show'
  end

  def show
  end

  def destroy
    @page.delete
		flash[:danger] = t(:page_deleted)
    redirect_to pages_path
  end

  def search
    @page = Page.find_by id: params[:q]
    if @page.nil?
      flash[:not_found] = t(:page_not_found)
      redirect_to pages_path
    else
      redirect_to page_path(@page)
    end
  end

  def about
  end

	private
		def page_params
			params.require(:page).permit( :title, :description )
		end
		def set_page
			@page = Page.find(params[:id])
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
<div class="container">
	<footer>
		<small>
			<p><%=t :copyright%></p>
		</small>
		<nav>
			<ul>
				<li><%= link_to "About", about_path %></li>
			</ul>
		</nav>
	</footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
	<div class="col-xs-10 col-xs-offset-1">
<% flash.each do |name,msg| %>
		<div class='alert alert-<%="#{name}" %>' >
			<a href class="close" data-dismiss="alert">&#215;</a>
				<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
		</div>
			<% if name.eql?("notice") %>
				<p class="alert alert-success"><%= msg %></p>
			<% elsif name.eql?("not_found") %>
				<p class="alert alert-danger"><%= msg %></p>
			<% end %>
		<% end %>
	</div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" >
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only"><%= t :toggle_navigation %></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Alpha Blog', root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to t(:pages), pages_path %><span class="sr-only">(current)</span></li>
        <li><%= link_to t(:new_page), new_page_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#"><%= t :action %></a></li>
            <li><a href="#"><%= t :another_action %></a></li>
            <li><a href="#"><%= t :something_else_here %></a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#"><%= t :separated_link %></a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#"><%= t :one_more_separated_link %></a></li>
          </ul>
        </li>
      </ul>
      <%= form_tag("/search", method: "get", class:"navbar-form navbar-left") do %>
        <div class="form-group">
          <%= text_field_tag(:q) %>
        </div>
        <%= submit_tag("Search", class:"btn btn-default") %>
      <% end %>
			<ul class="navbar-nav navbar-right" style="list-style:none;padding: 0px">
				<li style="margin: 0px 2px"><%= link_to image_tag("pt.gif", width: "20"), locale: :pt %></li>
				<li style="margin: 0px 2px"><%= link_to image_tag("eua.jpg", width: "20"), locale: :en %></li>
      </ul>
			<ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#"><%= t :action %></a></li>
            <li><a href="#"><%= t :another_action %></a></li>
            <li><a href="#"><%= t :something_else_here %></a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#"><%= t :separated_link %></a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<%= debug(params) if Rails.env.development? %>
  <%= render 'layouts/navbar' %>
  <%= render 'layouts/messages' %>
	<div class="container">
		<%= yield %>
	</div>
	<%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/_form.html.erb
<%= render 'shared/errors', obj: @page %>
<div class='row'>
	<div class='col-xs-12'>
		<%= form_for @page, html: {class: "form-horizontal", role: "form"} do |f|%>
			<div class="form-group">
				<div class="col-sm-2 control-label">
					<%= f.label t(:title) %>
				</div>
				<div class="col-sm-8">
					<%= f.text_field :title, class: "form-control", placeholder: "Title of page", autofocus: true %>
				</div>
			</div>
			<div class="form-group">
				<div class="col-sm-2 control-label">
					<%= f.label t(:description), style: "vertical-align: top" %>
				</div>
				<div class="col-sm-8">
					<%= f.text_area :description, rows:10, class: "form-control", placeholder: "Description of page" %> <br/>
				</div>
			</div>
			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-10">
					<%= f.submit class: "btn btn-default btn-lg" %>
				</div>
			</div>
		<% end %>
	</div>
<div>

app/views/pages/about.html.erb
<html>
  <header id="header"><h1><%= t :header, scope: [:about]  %></h1></header>
  <body>
    anything here
  </body>
</html>
<%= link_to 'Home', root_path %>

app/views/pages/edit.html.erb
<h1 align="center"> Editing a existing page </h1>
<%= render 'form' %>

app/views/pages/home.html.erb
<div class="jumbotron">
 <div class="container center">
   <header id="header center" class="center"><h1><%= t :header, scope: [:home] %></h1></header>
	 	<p><a class="btn btn-primary btn-lg btn-xlarge" href="#" role="button"><%= t :sign_up, scope: [:home] %></a></p>
    <%= link_to 'Index', pages_path %>
  </div>
</div>

app/views/pages/index.html.erb
<h1 align="center"><%= t :pages_header, scope: [:index] %></h1>
<% @pages.each do |page| %>
	<div class="row">
		<div class="col-xs-8 col-xs-offset-2">
			<div class="well well-lg">
				<div class="page-title">
					<%= link_to page.title, page_path(page) %>
				</div>
				<div class="page-body">
					<%= truncate(page.description, length: 100) %>
				</div>
				<div class="page-meta-datails">
					<!--diz quem foi o usario que criou a página, se o valor usuario para aquela pagina for nulo então escreve a palavra ninguém-->
					<small><%= t :created_by %> <%= page.user ? page.user.name : "ninguém"  %>, <%= time_ago_in_words(page.created_at) %> </small>
				</div>
				<div class="page-actions">
					<%= link_to t(:edit, scope: [:index]), edit_page_path(page), class: "btn btn-xs btn-primary" %>
					<%= link_to t(:delete, scope: [:index]), page_path(page), method: :delete, data: {confirm: t(:confirm, scope: [:index])}, class: "btn btn-xs btn-danger" %>
				</div>
			</div>
		</div>
	</div>
<% end %>

app/views/pages/new.html.erb
<h1 align="center"> <%= t :creating_page %> </h1>
<%= render 'form' %>

app/views/pages/show.html.erb
<h2 align="center"> <%= t :title %> <%= @page.title %> </h2>
<div class="well col-xs-8 col-xs-offset-2">
	<h4 class="center description"><strong> <%= t :description %> </strong></h4>
	<hr>
	<%= simple_format(@page.description) %>
	<div class="page-actions">
		<%= link_to 'Edit', edit_page_path(@page), class: "btn btn-xs btn-primary" %>
		<%= link_to 'Delete', page_path(@page), method: :delete, data: {confirm: t(:confirm, scope: [:index])}, class: "btn btn-xs btn-danger" %>
		<%= link_to 'Index', pages_path, class: "btn btn-xs btn-success" %>
	</div>
</div>

app/views/shared/_errors.html.erb
<%if obj.errors.any? %>
	<div class="row">
		<div class="col-xs-8 col-xs-offset-2">
			<div class="panel panel-danger">
				<div class="panel-heading">
					<h2 class="panel-title">
					<%= pluralize(obj.errors.count, "erro") %>
					prohibited this page from being saved:
					<div class="panel-body">
						<ul>
							<% obj.errors.full_messages.each do |msg| %>
								<li> <%= msg %> </li>
							<% end %>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
<% end %>